# Generated by Django 5.1.7 on 2025-03-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_once', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donateonce',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='donateonce',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
