# Generated by Django 5.1.7 on 2025-03-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_once', '0002_rename_created_at_donateonce_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateonce',
            name='site',
            field=models.CharField(choices=[('x.com', 'x.com'), ('y.com', 'y.com')], default='x.com', max_length=10),
        ),
    ]
