# Generated by Django 5.1.7 on 2025-03-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_once', '0003_donateonce_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateonce',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
    ]
