# Generated by Django 5.1.7 on 2025-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_once', '0004_alter_donateonce_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateonce',
            name='merchantTransactionId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donateonce',
            name='merchantUserId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donateonce',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
