# Generated by Django 5.1.7 on 2025-03-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate_once', '0005_donateonce_merchanttransactionid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donateonce',
            old_name='merchantTransactionId',
            new_name='merchant_transaction_idd',
        ),
        migrations.RenameField(
            model_name='donateonce',
            old_name='merchantUserId',
            new_name='merchant_user_id',
        ),
    ]
