# Generated by Django 5.1.7 on 2025-03-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate_once', '0006_rename_merchanttransactionid_donateonce_merchant_transaction_idd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donateonce',
            old_name='merchant_transaction_idd',
            new_name='merchant_transaction_id',
        ),
    ]
