# Generated by Django 5.1.7 on 2025-03-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_once', '0007_rename_merchant_transaction_idd_donateonce_merchant_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateonce',
            name='call_back_status',
            field=models.BooleanField(default=False),
        ),
    ]
