# Generated by Django 5.1.7 on 2025-03-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_once', '0008_donateonce_call_back_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateOnceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_once_response', models.JSONField(default=dict)),
                ('callback_response', models.JSONField(default=dict)),
                ('status_api_response', models.JSONField(default=dict)),
                ('cancelation_api_response', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
