# Generated by Django 5.1.7 on 2025-03-31 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_once', '0009_donateoncelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateoncelog',
            name='donate_once',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='donate_once.donateonce'),
        ),
    ]
